vim.cmd.source("~/.dotfiles/nvim/lua/config/functions/remove-quickfix-item.vim")

return {
    accept_ai_suggestion = require("config.functions.accept-suggestion"),
    clear_ai_suggestion = require("config.functions.clear-suggestion"),
    convert_to_camel_case = require("config.functions.convert-to-camel-case"),
    convert_to_dot_case = require("config.functions.convert-to-dot-case"),
    convert_to_kebab_case = require("config.functions.convert-to-kebab-case"),
    convert_to_lower_case = require("config.functions.convert-to-lower-case"),
    convert_to_pascal_case = require("config.functions.convert-to-pascal-case"),
    convert_to_snake_case = require("config.functions.convert-to-snake-case"),
    convert_to_upper_case = require("config.functions.convert-to-upper-case"),
    copy_absolute_file_path = require("config.functions.copy-absolute-file-path"),
    copy_current_branch_name = require("config.functions.copy-current-branch-name"),
    copy_project_file_path = require("config.functions.copy-project-file-path"),
    copy_project_file_path_and_line_number = require("config.functions.copy-project-file-path-and-line-number"),
    debug_function = require("config.functions.debug-function"),
    debug_test = require("config.functions.debug-test"),
    delete_debug_statements = require("config.functions.delete-debug-statements"),
    delete_line = require("config.functions.delete-line"),
    generate_function = require("config.functions.generate-function"),
    goto_javascript_import = require("config.functions.goto-javascript-import"),
    insert_debug_print_statement = require("config.functions.insert-debug-print-statement"),
    insert_debug_variable_statement = require("config.functions.insert-debug-variable-statement"),
    open_filetree = require("config.functions.open-filetree"),
    open_git_commits_with_file = require("config.functions.open-git-commits-with-file"),
    open_git_diff_with_master = require("config.functions.open-git-diff-with-master"),
    open_git_diff_with_pr_base = require("config.functions.open-git-diff-with-pr-base"),
    open_git_file_diff_with_pr_base = require("config.functions.open-git-file-diff-with-pr-base"),
    open_github_pr_comment = require("config.functions.open-github-pr-comment"),
    open_quickfix_of_search_term = require("config.functions.open-quickfix-of-search-term"),
    open_terminal = require("config.functions.open-terminal"),
    run_import_code_action = require("config.functions.run-import-code-action"),
    search_buffers = require("config.functions.search-buffers"),
    search_dotfiles = require("config.functions.search-dotfiles"),
    search_files = require("config.functions.search-files"),
    search_project_file_contents = require("config.functions.search-project-file-contents"),
    search_project_files = require("config.functions.search-project-files"),
    search_project_html_usages = require("config.functions.search-project-html-usages"),
    search_quickfix_list = require("config.functions.search-quickfix-list"),
    search_recent_files = require("config.functions.search-recent-files"),
    split_window_horizontally = require("config.functions.split-window-horizontally"),
    split_window_vertically = require("config.functions.split-window-vertically"),
    toggle_ai_suggestions = require("config.functions.toggle-ai-suggestions"),
    toggle_formatting_on_save = require("config.functions.toggle-formatting-on-save"),
    toggle_line_wrap = require("config.functions.toggle-line-wrap")
}
