plugin:
  windows-shell:
    shortCut: w
    description: "Shell (Windows)"
    scopes:
      - containers
      - pods
    command: sh
    background: false
    confirm: false
    args:
      - -c
      - "kubectl exec -it -n $NAMESPACE $POD -- powershell.exe"

  toggle-cronjob:
    shortCut: Ctrl-S
    confirm: true
    scopes:
      - cj
    description: Toggle CronJob Suspension
    command: kubectl
    background: true
    args:
      - patch
      - cronjobs
      - $NAME
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT
      - -p
      - '{"spec" : {"suspend" : $!COL-SUSPEND }}'

  backup-resource:
    shortCut: b
    description: "Backup Resource"
    scopes:
      - all
    command: sh
    background: false
    confirm: false
    args:
      - -c
      - |
        FILENAME=$RESOURCE_NAME-$NAME-$(date +%s).yaml && \
        kubectl get $RESOURCE_NAME $NAME --namespace $NAMESPACE --context $CONTEXT -o yaml 2>&1 > $FILENAME && \
        "$EDITOR" "$FILENAME"
